export type ClientModel = {
   IC_PASSPORT_NO: string; 
   STATE?: string;
   ETHNICITY?: string
   SPECIAL_CAT_POP?: boolean;
   COMOROBIDITY?: boolean;
   OUTREACH_MODE: string;
   OUTREACH_METHOD?: string;
   EMPLOYMENT_STATUS?: string;
   KEY_POPULATION: string;
   COMMUNITY_SERVICE_KDK_IF_PWUD?: boolean;
   RISK_BEHAVIOUR?: boolean;
   RISK_BEHAVIOUR_OPTION?: Array<string>;
   MMT_PROGRAM_REFERRAL_IF_INJECTING_DRUG_USER?: string;
   COMMODITIES?: boolean;
   CONDOM?: number;
   LUBS?: number;
   NEEDLE_GIVEN?: number;
   NEEDLE_COLLECTED?: number;
   SYRINGE_GIVEN?: number;
   SYRINGE_COLLECTED?: number;
   HIV_SCREENING?: boolean;
   HIV_SCREENING_RESULT_IF_YES?: string;
   CONFIRMATORY_TEST?: boolean;
   OPTIONS_FOR_CONFIRMATORY_TEST?: Array<string>;
   REFERRAL_FOR_PREP?: boolean
   OPTIONS_FOR_REFERAL_FOR_PREP?: string;
   HIV_SCREENING_RESULT_IF_NO?: string;
   TREATMENT_IF_HAS_TESTED_POSITIVE_HIV?: string;
   REASON_IF_TREATMENT_NO?: string;
   SYP_SCREENING?: boolean;
   SYP_REASON_IF_NO?: string;
   SYP_OPTIONS_IF_YES?: string;
   SYP_CONFIRMATORY_TEST?: boolean;
   SYP_OPTIONS_FOR_CONFIRMATORY_TEST_NO?: string;
   HEP_C_SCREENING?: boolean;
   HEP_C_REASON_IF_NO?: string;
   HEP_C_OPTIONS_IF_YES?: string;
   HEP_C_CONFIRMATORY_TEST?: boolean
   HEP_C_OPTIONS_FOR_CONFIRMATORY_TEST_NO?: string;
   PERFORMED_BY?: string;
   VOLUNTEER_EMAIL: string;
   NGO_ID_NUMBER?: string;
   NGO_NAME?: string;
   SCREENING_DATE?: Date;
   MYVAS_ACCOUNT?: string;
}